services:
  db:
    image: mysql:8.0
    container_name: db_aya
    restart: always
    environment:
      MYSQL_DATABASE: 'aya_db'
      MYSQL_USER: 'user_aya'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  s3:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      MINIO_ROOT_USER: usr_minio
      MINIO_ROOT_PASSWORD: minio_pw
      MINIO_ACCESS_KEY: aws_access_key
      MINIO_SECRET_KEY: aws_secret_key
      MINIO_DEFAULT_BUCKETS: aya
    command: server --console-address ":9001" /data
volumes:
  my-db: 
    driver: local
  minio_data:
    driver: local

networks:
  minionetwork:
    driver: bridge