# Generated by Django 5.1.6 on 2025-02-21 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_categoria_tipo_lancamento'),
        ('empresas', '0004_alter_empresa_cnpj_alter_empresa_nome_razao_social_and_more'),
        ('fornecedores', '0002_rename_whataspp_fornecedor_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoDeCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissão', models.DateField(verbose_name='Data Emissão')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('valor_moeda_estrangeira', models.IntegerField(null=True, verbose_name='Moeda Estrangeira')),
                ('valor_cotacao', models.IntegerField(null=True, verbose_name='Cotação Moeda')),
                ('data_vencimento', models.DateField(verbose_name='Data Vencimento')),
                ('data_pagamento', models.DateField(null=True, verbose_name='Data Pagamento')),
                ('conta_corrente', models.CharField(max_length=50, null=True, verbose_name='Conta Corrente')),
                ('projeto', models.CharField(max_length=50, null=True, verbose_name='Projeto')),
                ('forma_pagamento', models.CharField(max_length=30, null=True, verbose_name='Forma Pagamento')),
                ('num_documento', models.BigIntegerField(null=True, verbose_name='Número Documento')),
                ('parcelas', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='categorias.categoria', verbose_name='Categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fornecedores.fornecedor', verbose_name='Fornecedor')),
            ],
        ),
    ]
