# Generated by Django 5.1.6 on 2025-02-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_tipo_lancamento'),
        ('empresas', '0004_alter_empresa_cnpj_alter_empresa_nome_razao_social_and_more'),
        ('fluxo_caixa', '0001_initial'),
        ('fornecedores', '0002_rename_whataspp_fornecedor_whatsapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FluxoDeCaixa',
            new_name='FluxoCaixa',
        ),
        migrations.AlterModelOptions(
            name='fluxocaixa',
            options={'verbose_name': 'fluxo_caixa', 'verbose_name_plural': 'fluxo_caixa'},
        ),
        migrations.AlterModelTable(
            name='fluxocaixa',
            table='fluxos_caixa',
        ),
    ]
