# Generated by Django 5.1.6 on 2025-02-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_caixa', '0002_rename_fluxodecaixa_fluxocaixa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxocaixa',
            old_name='data_emissão',
            new_name='data_emissao',
        ),
    ]
