# Generated by Django 5.1.6 on 2025-02-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_caixa', '0003_rename_data_emissão_fluxocaixa_data_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxocaixa',
            name='forma_pagamento',
            field=models.CharField(choices=[('Boleto', 'Boleto'), ('Cartão Crédito', 'Cartão Crédito'), ('Débito', 'Débito'), ('Pix', 'Pix')], max_length=30, null=True, verbose_name='Forma Pagamento'),
        ),
    ]
