# Generated by Django 5.1.6 on 2025-02-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_caixa', '0006_alter_fluxocaixa_valor_cotacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxocaixa',
            name='valor_cotacao',
            field=models.FloatField(default=None, null=True, verbose_name='Cotação Moeda'),
        ),
        migrations.AlterField(
            model_name='fluxocaixa',
            name='valor_moeda_estrangeira',
            field=models.FloatField(default=None, null=True, verbose_name='Moeda Estrangeira'),
        ),
    ]
