# Generated by Django 5.1.6 on 2025-02-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_caixa', '0007_alter_fluxocaixa_valor_cotacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxocaixa',
            name='num_documento',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Número Documento'),
        ),
        migrations.AlterField(
            model_name='fluxocaixa',
            name='num_parcela',
            field=models.IntegerField(default=1, null=True, verbose_name='Número Parcela'),
        ),
        migrations.AlterField(
            model_name='fluxocaixa',
            name='parcelas',
            field=models.IntegerField(default=1, null=True, verbose_name='Parcelas'),
        ),
    ]
