# Generated by Django 5.1.6 on 2025-03-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_caixa', '0009_alter_fluxocaixa_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxocaixa',
            name='arquivo',
            field=models.FileField(null=True, upload_to='fluxo-caixa/arquivos', verbose_name='Arquivo'),
        ),
    ]
