# Generated by Django 5.1.6 on 2025-03-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_remove_categoria_categoria_remove_categoria_user_and_more'),
        ('centro_custos', '0001_initial'),
        ('fluxo_caixa', '0010_fluxocaixa_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxocaixa',
            name='centro_custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='centro_custos.centrocusto', verbose_name='Centro de Custo'),
        ),
        migrations.AlterField(
            model_name='fluxocaixa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria', verbose_name='Categoria'),
        ),
    ]
