# Generated by Django 5.1.6 on 2025-02-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_tipo_lancamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('RECEITAS', 'Receitas'), ('CUSTOS E DESPESAS', 'Custos e Despesas'), ('CUSTOS DE PRODUÇÃO INDUSTRIAL', 'Custos de Produção Industrial'), ('CUSTOS DA PRESTAÇÃO DE SERVIÇOS', 'Custos de Prestação de Serviços'), ('DESPESAS OPERACIONAIS', 'Despesas Operacionais'), ('OUTROS CUSTOS/DESPESAS OPERACIONAIS', 'Outros Custos/Despesas Operacionais'), ('RESULTADO', 'Resultado')], default=None, max_length=100, unique=True, verbose_name='Categorias'),
            preserve_default=False,
        ),
    ]
