# Generated by Django 5.1.6 on 2025-03-04 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_alter_categoria_options_remove_categoria_categoria_and_more'),
        ('tipo_lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='user',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipo_lancamentos.tipolancamento', verbose_name='Tipo Lançamento'),
        ),
    ]
